### ISSUE TITLE
Proxy for HTTP requests

### ISSUE THREAD

**Issue by bengower** [crawlzone/crawlzone#5]
Hello,

Have you considered routing HTTP requests through multiple IP addresses using a proxy service to get round some anti-crawling measures?

**Comment by zstate** [comment]
Hi @bengower, thanks for the feedback. Currently you can use `proxy` setting like that:

```
$config = [
    'start_uri' => ['http://test.com'],
    'concurrency' => 5,
    'request_options' => [
        'proxy' => [
            'http'  => 'tcp://localhost:8125', // Use this proxy with "http"
            'https' => 'tcp://localhost:9124', // Use this proxy with "https",
            'no' => ['.mit.edu', 'foo.com']    // Don't use a proxy with these
        ],
    ]
];
```

Also you can  re-route the requests with the request middleware. Hope this helps.
